version: "3.8"

networks:
  general_default:
    ipam:
      driver: default
      config:
        - subnet: 198.18.55.0/30
  hub:
    external:
      name: rb_hub_general_leaf
  console:
    external:
      name: rb_console_general

services:
  general:
    restart: unless-stopped
    hostname: general
    domainname: netwerk.insecurity.corp
    userns_mode: "host"
    build:
      context: ../ratbox
      dockerfile: Dockerfile
    image: ratbox:latest
    command: "/usr/local/ircd/bin/ircd -pidfile /run/ircd.pid -foreground || /usr/local/ircd/bin/ircd -conftest"
    environment:
      LANG: en_US.utf8
      TZ: UTC
      NICK_LEN: 32
    ulimits:
      nproc: 65535
      nofile:
        soft: 1024000
        hard: 1024000
    networks:
      general_default:
        ipv4_address: 198.18.55.2
      hub:
        ipv4_address: 198.18.70.3
      console:
        ipv4_address: 198.18.70.50
    volumes:
      - ../etc/:/usr/local/ircd/etc:rw
      - ./general.conf:/usr/local/ircd/etc/ircd.conf:ro
      - ../ephemeral/logs:/usr/local/ircd/logs:rw
      - ../ephemeral/db:/usr/local/ircd/ephemeral/db:rw
