# 100.64.48.24/30 100.64.66.96/27

version: "3.8"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 100.64.48.24/30

services:
  hopm:
    restart: unless-stopped
    hostname: h0pm.n3tw3rk.1ns3cur1ty.c0rp
    build:
      context: ../hopm
      dockerfile: Dockerfile
    image: hopm:latest
    command: "/usr/local/hopm/bin/hopm"
    environment:
      LANG: en_US.utf8
      TZ: UTC
    ulimits:
      nproc: 65535
      nofile:
        soft: 1024000
        hard: 1024000
    networks:
      default:
        ipv4_address: 100.64.48.26
    volumes:
      - type: volume
        source: ephemeral
        target: /usr/local/hopm/var
        volume:
          nocopy: false
      - ../config/hopm:/usr/local/hopm/etc:ro

volumes:
  ephemeral:
