# https://docs.docker.com/compose/compose-file/

# 100.64.48.4/30 100.64.65.64/26

version: "3.8"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 100.64.48.4/30
  mysql:
    external:
      name: hb_mysql_postfix
  anope:
    ipam:
      driver: default
      config:
        - subnet: 100.64.65.64/29
    internal: true

services:
  postfix:
    restart: unless-stopped
    hostname: p0stf1x.n3tw3rk.1ns3cur1ty.c0rp
    build:
      context: ../postfix
    image: postfix:latest
    command: "supervisord -c /postfix/configs/supervisor/supervisord.conf"
    networks:
      default:
        ipv4_address: 100.64.48.6  
      mysql:
        ipv4_address: 100.64.64.139
      anope:
        ipv4_address: 100.64.65.66
    volumes:
      - type: volume
        source: ephemeral
        target: /var/lib/postfix
        volume:
          nocopy: false
      - ../config/postfix:/postfix/configs:ro
    ulimits:
      nproc: 65535
      nofile:
        soft: 1024000
        hard: 1024000

volumes:
  ephemeral:
