# https://docs.docker.com/compose/compose-file/

# 100.64.0.0/30 100.64.64.0/25

version: "3.8"

networks:
  hub_default:
    ipam:
      driver: default
      config:
        - subnet: 100.64.0.0/30
  general_leaf:
    ipam:
      driver: default
      config:
        - subnet: 100.64.64.0/29
    internal: true
  tor_leaf:
    ipam:
      driver: default
      config:
        - subnet: 100.64.64.8/29
    internal: true
  proxy_leaf:
    ipam:
      driver: default
      config:
        - subnet: 100.64.64.16/29
    internal: true
  edge_leaf:
    ipam:
      driver: default
      config:
        - subnet: 100.64.64.24/29
    internal: true
  services:
    ipam:
      driver: default
      config:
        - subnet: 100.64.64.32/29
    internal: true
  bounce:
    ipam:
      driver: default
      config:
        - subnet: 100.64.64.40/29
    internal: true
  console:
    ipam:
      driver: default
      config:
        - subnet: 100.64.64.48/29
    internal: true

services:
  hub:
    restart: unless-stopped
    hostname: hub.n3tw3rk.1ns3cur1ty.c0rp
    build:
      context: ../hybrid
      dockerfile: Dockerfile
    image: hybrid:latest
    command: "/usr/local/ircd/bin/ircd -foreground -pidfile /dev/shm/ircd.pid -configfile /usr/local/ircd/etc/ircd.conf -logfile /dev/stdout"
    environment:
      LANG: en_US.utf8
      TZ: UTC
    ulimits:
      nproc: 65535
      nofile:
        soft: 1024000
        hard: 1024000
    networks:
      hub_default:
        ipv4_address: 100.64.0.2
      general_leaf:
        ipv4_address: 100.64.64.2
      tor_leaf:
        ipv4_address: 100.64.64.10
      proxy_leaf:
        ipv4_address: 100.64.64.18
      edge_leaf:
        ipv4_address: 100.64.64.26
      services:
        ipv4_address: 100.64.64.34
      bounce:
        ipv4_address: 100.64.64.42
      console:
        ipv4_address: 100.64.64.50
    volumes:
      - type: volume
        source: hb_hub_ephemeral
        target: /usr/local/ircd/var
        volume:
          nocopy: false
      - ../config/hybrid:/usr/local/ircd/etc/hb_conf:ro
      - ./ircd.conf:/usr/local/ircd/etc/ircd.conf:ro

volumes:
  hb_hub_ephemeral:
