# https://docs.docker.com/compose/compose-file/

# 100.64.0.16/30 100.64.66.0/27

version: "3.8"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 100.64.0.16/30
  console:
    ipam:
      driver: default
      config:
        - subnet: 100.64.66.0/29
  hub:
    external:
      name: hb_hub_tor_edge_hub
  tor:
    external:
      name: hb_tor_hub

services:
  edge:
    restart: unless-stopped
    hostname: t0r-3dg3.n3tw3rk.1ns3cur1ty.c0rp
    build:
      context: ../hybrid
      dockerfile: Dockerfile
    image: hybrid:latest
    command: "/usr/local/ircd/bin/ircd -foreground -pidfile /dev/shm/ircd.pid -configfile /usr/local/ircd/etc/hb_conf/tor-edge.conf -logfile /dev/stdout"
    environment:
      LANG: en_US.utf8
      TZ: UTC
    ulimits:
      nproc: 65535
      nofile:
        soft: 1024000
        hard: 1024000
    networks:
      default:
        ipv4_address: 100.64.0.18
      console:
        ipv4_address: 100.64.66.2
      hub:
        ipv4_address: 100.64.64.59
      tor:
        ipv4_address: 100.64.65.11
    volumes:
      - type: volume
        source: ephemeral
        target: /usr/local/ircd/var
        volume:
          nocopy: false
      - ../config/hybrid:/usr/local/ircd/etc/hb_conf:ro

volumes:
  ephemeral:
